### ISSUE TITLE
Getting a 404 error

### ISSUE THREAD

**Issue by waleakande** [kinngh/shopify-express-mongodb-app#1]
I followed your instructions. When I try to install the app from the Partners dashboard it redirects me to a 404 page.

**Comment by waleakande** [comment]
I wanted to give a quick update, when I try to install the app it attempts to take me through the installation process. It then times out after 3mins. It returning a 504 error now.

**Comment by kinngh** [comment]
Can I have more info into what's your setup like? Like Localtunnel, Mongo and other configuration? Because I've been working on this template as a starter for 2 production grade apps and the boilerplate works out of the box, so I'm pretty sure it's just a configuration issue and the documentation needs to be clearer on setting up the repo

**Comment by waleakande** [comment]
I figure it out my configuration was off earlier.

**Comment by kinngh** [comment]
Glad you figured it out! Please feel free to open any issues if they pop up!

**Comment by ivorpad** [comment]
@waleakande What was off in your config? I keep getting the same 502.

@kinngh Why are you exporting `createServer`? I suggest using named exports tho.

**Comment by kinngh** [comment]
> @kinngh Why are you exporting `createServer`? I suggest using named exports.
> 
> When running `npm run dev` the server is not starting (`createServer` never gets called)


@ivorpad The implementation is half done. Currently it runs in production mode only, I had some issues with dev mode so that's still pending. The issue is on my end because I should have made it clear that dev mode with HMR is currently under testing.

**Comment by kinngh** [comment]
Ref comments on commit [71dcc47](https://github.com/kinngh/shopify-express-mongodb-app/commit/71dcc475f6b930ccbc69cad37d4260359ce61f11)
