### ISSUE TITLE
Dev mode is currently broken

### ISSUE THREAD

**Issue by kinngh** [kinngh/shopify-express-mongodb-app#2]
The `npm run dev` is currently broken leading to a lot of 4xx and 5xx errors since the dev mode implementation is half baked. The production mode runs just fine with `npm run build` followed by a `npm run start`. HMR isn't supported in production mode, so any changes to React side of things need a `npm run build` and refresh in the embedded app to update.

**Comment by ivorpad** [comment]
A couple of issues:

1. I suggest changing `isTest` to `isDev` and avoid using it like `!isDev` as it is confusing. Instead:

`if(isDev) // do dev things`

If you have `isDev` then `isProd` is not necessary.

2. Calling the `middlewares` method in `vite` throws an error because you're not returning in `server/index.js` line 98.

Should be:

```js
vite = await import("vite").then(({ createServer }) =>
  createServer({
    root,
    logLevel: isDevelopment ? "error" : "info",
    server: {
      port: PORT,
      hmr: {
        protocol: "ws",
        host: "localhost",
        port: 64999,
        clientPort: 64999,
      },
      middlewareMode: "html",
    },
  })
);
```

`() => {} // undefined` vs `() => ({}) // {}`

**Comment by kinngh** [comment]
After reading some documentation, `npm run dev` is now working again. Also thanks to your fix for vite! 

Commit [1fde536](https://github.com/kinngh/shopify-express-mongodb-app/commit/1fde536df02460b488e65089d14e3963c5d7824f) temporarily fixes the issue. I am currently taking a look at the whole `isProd` / `isTest` blunder that creeped in.

Anyways, thank you for bringing this to my notice and suggesting changes, @ivorpad !

**Comment by kinngh** [comment]
Update: [fbd0f8d](https://github.com/kinngh/shopify-express-mongodb-app/commit/fbd0f8d50c6610ba7a06590992b561a8542889e0) fixes issues created in 1dfe536 and implements `isDev` instead of multi-variable mess. 

Again, thank you for bringing this up!

**Comment by patrickbolle** [comment]
@kinngh Do you know how we could get this working with Shopify's HMR fixes for Safari/Firefox?

They seem to have fixed it in combination with their newest CLI upgrade and updated docs here: https://github.com/Shopify/shopify-app-template-node/pull/984

I've tried putting in their hmrConfig code into your template, but it doesn't work - no front-end changes are shown until reloading page.

**Comment by kinngh** [comment]
@patrickbolle let me take a look at this. I'm currently down with a terrible viral fever, so it could be another few days before I'm back on track^

**Comment by kinngh** [comment]
@patrickbolle transferring this to a separate issue #22
